Feature/forms
errea/forms-reformer-rails-app pull request #1
Opened 2021-04-16 15:43 UTC by errea

# Description

This PR is requested based on the project on building forms with Rails which include the following:  
- [x] User routes should be only available for new, create, edit, update
- [x] edit actions should find a user based on id from params
- [x] Create should redirect to new user path when user saved
- [x] The update should redirect to edit user if saved successfully
- [x] User params should include username, password, and email
- [x]  form_with uses @user 

# Type of Fix

- [x] Rubocop fix
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This app has been tested via deployment on Heroku and on the Localhost:3000
- [x] Heroku
- [x] Local Host

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-04-16 19:42 UTC, GzimAsani requested changes
# STATUS: Changes Required :red_circle: :recycle: 

### Hello @errea, your project looks really good :+1: 

### To highlight:
- You have done good job with models/database
- Your project looks professional :+1: 

### To improve:

- [x] Add and comment out forms that use the normal form and form_tag
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] In readme file under installation section add that a user needs to run rails db:migrate to migrate your files
- [ ] Your live deployment is returning 404 error. Hint: you are not required to provide live link for this project so either remove or add a live link that works
- [  OPTIONAL ] Add a picture of your project in readme file. It will look more professional 

_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

# HAPPY CODING :computer: :desktop_computer:

2021-04-16 19:42 UTC, GzimAsani commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Remove commented out code

2021-04-16 19:42 UTC, GzimAsani commented on app/controllers/users_controller.rb
> +      # redirect_to root_path(@user)
Remove commented out code

2021-04-17 11:07 UTC, GzimAsani requested changes
# STATUS: Changes Required :red_circle: 

## Hello @errea,  thank you for implementing almost all the required changes but please also implement the following that was asked previously:

- [ ]  _Add and comment out forms that use the normal form and form_tag_

_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

# HAPPY CODING :computer: :desktop_computer:

2021-04-17 14:39 UTC, errea commented
@GzimAsani Please I left a message for you on slack.

2021-04-18 20:24 UTC, uryelah approved these changes
Hi **Eri Okereafor** , I'm Sarah your reviewer for this PR 👩‍🚀 

Good job adding the fixes required by the last reviewer!


# Approved 🚀 

You may merge your project and submit the completion form. 

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-04-18 20:24 UTC, uryelah commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 8 }
- [ ] [OPTIONAL] Add some formatting validations to email and password to make sure they are in the expected format, you can use regular expressions for that.

2021-04-19 07:51 UTC, merged